### ISSUE TITLE
woff2 is missing in published bower.json 4.3.0 

### ISSUE THREAD

**Issue by raphaelluchini** [components/font-awesome#24]
bower components-font-awesome#4.3.0         validate 4.3.0 against git://github.com/components/font-awesome.git#4.3.0

{
  name: 'components-font-awesome',
  description: 'Font Awesome, the iconic font designed for use with Twitter Bootstrap.',
  repository: {
    type: 'git',
    url: 'git://github.com/components/font-awesome.git'
  },
  main: [
    'css/font-awesome.css',
    'scss/font-awesome.scss',
    'fonts/fontawesome-webfont.eot',
    'fonts/fontawesome-webfont.woff',
    'fonts/fontawesome-webfont.ttf',
    'fonts/fontawesome-webfont.svg'
  ],
  license: [
    'MIT',
    'OFL-1.1'
  ],
  ignore: [
    'Makefile',
    'component.json',
    'composer.json'
  ],
  homepage: 'https://github.com/components/font-awesome',
  version: '4.3.0'
}

**Comment by martinlindhe** [comment]
this was updated in feb in commit https://github.com/components/font-awesome/pull/23, please use dev-master to get the fix or wait for a new version to be tagged

**Comment by bogdanalexe90** [comment]
when do you plan to release the next version?

**Comment by martinlindhe** [comment]
@bogdanalexe90: we tag versions according to the official releases, which is currently still 4.3.0:

https://fortawesome.github.io/Font-Awesome/

**Comment by RobLoach** [comment]
Another option is to delete the current tag and retag for what was updated in bower.json.

**Comment by martinlindhe** [comment]
@robloach: okay, but wont that mess up existing checkouts?
