### ISSUE TITLE
`components-font-awesome` package missing in npm

### ISSUE THREAD

**Issue by ducin** [components/font-awesome#27]
I'm giving up bower! It stopped to make sense to use both npm and bower. I'm migrating all bower dependencies indo npm:dependencies.

One of my dependencies in bower is `"components-font-awesome": "=3.2.1"`. I can't find it in npm: https://www.npmjs.com/package/components-font-awesome. As far as I understand it, the idea of `components` is to support as many managers as possible (https://github.com/components/components#package-managers), and npm here is missing. Could you publish the `components-font-awesome` package in npm?

Or if you don't have time, I can do that and afterwards transfer the ownership in npm - but please say so.

**Comment by ducin** [comment]
solved in #28, I'd happily transfer npm package ownership to appropariate maintainers.

**Comment by RobLoach** [comment]
@ducin Excellent! Thnaks a lot.... Mind adding me, and a few others to the npm package? I'll add you to the github too.

**Comment by ducin** [comment]
@RobLoach I will happily add everybody, just let me know the usernames :)
https://www.npmjs.com/package/components-font-awesome

**Comment by RobLoach** [comment]
Just `robloach` for now, I can add more if needed. :+1:

**Comment by ducin** [comment]
YOu;ve been added @RobLoach :) https://www.npmjs.com/package/components-font-awesome
btw I've submitted *all* versions, but in a different order, I did 4.5.0, 4.4.0 then 3.x->4.3.0, sorry for that ;) the order is innatural, but everything is covered as it should be.
