### ISSUE TITLE
Description not descriptive

### ISSUE THREAD

**Issue by arfordweb** [components/font-awesome#35]
I'm having a little trouble understanding the description.

I understand how many folks use the term "shim" to mean giving older or incomplete technologies more capabilities to get to parity with better or more recent technologies.  But, it doesn't appear that's the intended meaning in the sentence "Shim repository for Font Awesome."  Could you expound on the meaning of this phrase and the purpose of this repo?  What would be the reason for using this over FontAwesome/Font-Awesome?

Thank you.

**Comment by RobLoach** [comment]
There are some general docs for this over at https://github.com/components/components . Mind creating an issue over there to expand on the docs a bit? Thanks!
