### ISSUE TITLE
Font Awesome 5

### ISSUE THREAD

**Issue by dmolineus** [components/font-awesome#46]
Is it planned to provide a version for Font Awesome 5 (free version)?

**Comment by franzliedke** [comment]
Apparently, [version 5.0.6](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.0.6) has now been released on GitHub.

**Comment by RobLoach** [comment]
:+1:

**Comment by RobLoach** [comment]
Thanks @afrastgeek!

**Comment by afrastgeek** [comment]
@RobLoach sure, my pleasure.
