### ISSUE TITLE
Font-Awesome 6.4.0 ... When?

### ISSUE THREAD

**Issue by dmikam** [components/font-awesome#57]
The latest version for composer is 6.2.0, but official Font-Awesome **6.4.2** is 4 months old now... When should we expect the update?

**Comment by Guite** [comment]
6.4.2 has been released 5 days ago, not 4 months.
Going to release it asap.

**Comment by Guite** [comment]
6.4.2 has just been released.
See https://github.com/components/font-awesome/releases/tag/6.4.2
See https://packagist.org/packages/components/font-awesome#6.4.2

**Comment by dmikam** [comment]
Sorry, 6.4.0 is 4 months old (27 of March 2023 - according to Wikipedia)

**Comment by dmikam** [comment]
Ohh!! Now I see 6.4.2 in composer!!!
Thanks a lot!!!
